name: simnibs_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - cgal-cpp=5.5
  - freeglut
  - h5py
  - jsonschema
  - libwebp
  - matplotlib-base
  - mkl
  - mock
  - nibabel
  - numba
  - pillow
  - pip
  - pyopengl
  - pytest
  - python-mumps
  - requests
  - scipy
  - setuptools-scm
  - tbb-devel
  - vs2015_runtime
  - zlib
  - jupyterlab
  - pip:
    - numpy>=2
    - cython
    - pygpc==0.4
    - PyQt5
    - https://download.pytorch.org/whl/cpu/torch-2.6.0%2Bcpu-cp311-cp311-win_amd64.whl#sha256=24c9d3d13b9ea769dd7bd5c11cfa1fc463fd7391397156565484565ca685d908
    - pytorch-ignite
    - brainsynth@git+https://github.com/simnibs/brainsynth@57fcdfe
    - brainnet@git+https://github.com/simnibs/brainnet@88fbb63
    - https://github.com/oulap/samseg_wheels/releases/download/dev/samseg-0.4a0+6.g3bdd30a-cp311-cp311-win_amd64.whl
    - https://github.com/simnibs/cortech/releases/download/v0.1/cortech-0.1-cp311-cp311-win_amd64.whl
    - https://github.com/simnibs/fmm3dpy/releases/download/v1.0.4/fmm3dpy-1.0.4-cp311-cp311-win_amd64.whl
    - https://github.com/simnibs/petsc4py/releases/download/v3.22.2/petsc4py-3.22.2-cp311-cp311-win_amd64.whl
